### PR TITLE
doc(github-issue-hacktoberfest): include orientation video

### PR DESCRIPTION
**Pull request by ShihChun-H**
Because

- video is done

This commit

- include video link and description

### CODE REVIEW

**Comment by ShihChun-H** [comment]
@xiaofei-du Does it have to follow the guideline as well?
https://github.com/instill-ai/instill.tech/blob/main/.github/DOCS-CONTRIBUTING.md#youtube

**Comment by xiaofei-du** [comment]
> @xiaofei-du Does this have to follow the guideline as well? https://github.com/instill-ai/instill.tech/blob/main/.github/DOCS-CONTRIBUTING.md#youtube

Yes, please!

**Comment by ShihChun-H** [comment]
@all-contributors please add @ShihChun-H for content.

**Comment by ShihChun-H** [comment]
@all-contributors please add @ShihChun-H for content.

**Pull request closed without merging**
